### ISSUE TITLE
Use compression for transfer of JSON

### ISSUE THREAD

**Issue by ties** [bgp/stayrtr#100]
The file with validated objects is growing and starting. Depending on the output style, I see 43MB (current rpki-client output), 57MB (jq or new rpki-client builds, one attribute per line, no colour, indented), while compact JSON is ~37M (`jq -c`).

It compresses pretty well.

Because the client trusts the server (w.r.t. content) I do not think gzip bombs are an issue. So, as a user, I want the HTTP client should use HTTP compression when loading the prefixes.

**Comment by benjojo** [comment]
The golang http library already does transparent gzip decompression, so
long as your webserver does it. it will be sent over the wire compressed!

I think that should be enough to allow people to have compressed pulls,
rather than adding logic in place to actively decompress files

**Comment by ties** [comment]
Nice feature. Did not have time to check this at the time. I've validated that the content is compressed (request to default `console.rpki-client.org` URL on Fastly):
<img width="1013" alt="Screenshot 2023-05-03 at 07 55 02" src="https://user-images.githubusercontent.com/199058/235841395-2b16d500-9248-4cc7-ba40-9e87ff815775.png">

Instrumenting a metric for the underlying length is a bit hard because chunked responses have `fhttp.ContentLength == -1` and the decompression is transparent. I will skip that one.
