### ISSUE TITLE
Does rtrdump actually downgrade the version?

### ISSUE THREAD

**Issue by partim** [bgp/stayrtr#122]
We’re having an issue in Routinator (https://github.com/NLnetLabs/routinator/issues/950) where rtrdump fails to produce any output when not started with `-rtr.version 1`. It does print “Downgrading to version 1” but then seems to just close the connection.  I did test with the fixed RTR server code that reports the expected version in the error PDU.

Can you confirm that this indeed because rtrdump doesn’t retry with the new version or is there something that Routinator does wrong?

**Comment by ties** [comment]
You can check what is sent with Wireshark.

I also hit this when using stayrtr as a library: there is a message but no actual version downgrade. I assumed this was an error in my usage.

**Comment by partim** [comment]
I checked with Wireshark – it just closes the connection after receiving the error. I’m asking because there were issues around this earlier and want to double check whether there are more fixes that are needed on my side.

**Comment by job** [comment]
Yes, `rtrdump` (at least on the `master` branch) downgrades:

```
$ ./dist/rtrdump-v0.5.1-62-g9416292-linux-x86_64
INFO[0000] Connecting with plain to 127.0.0.1:8282
INFO[0000] Downgrading to version 1
$ jq -c '.metadata' output.json
{"vrps":599727,"aspas":0,"bgpsec_pubkeys":0}
```
