### ISSUE TITLE
-version doesn't expose version

### ISSUE THREAD

**Issue by funzoneq** [bgp/stayrtr#123]
```
/usr/bin/stayrtr -version
StayRTR
```

I know the package has a version number, but it would be nice to have this reflected in the version string of the build.

**Comment by ties** [comment]
This is odd. On my local machine I get
```
$ make
...
$ ./dist/stayrtr-v0.5.1-49-g3b91cfa-linux-x86_64 -version
StayRTR v0.5.1-49-g3b91cfa (2024-05-04T09:39:53+0200)
```

What source are you using for stayrtr?

**Comment by randomthingsandstuff** [comment]
its a link-time variable. if you don't use the makefile, you're not going to get it.

**Comment by moshivji** [comment]
I also get the same ,

```
$ stayrtr -version
StayRTR  
$ 

```

**Comment by job** [comment]
@randomthingsandstuff how about just solving this as follows: https://github.com/bgp/stayrtr/pull/125

**Comment by mrngm** [comment]
If you have the Go toolchain (>= 1.18, which happens to be the minimum declared in `go.mod`) installed, you could also use

```
go version -m stayrtr
```

A fresh clone (and Go 1.22) of this repository gives:

```
$ git log | head -n1 && go build ./cmd/stayrtr/ && go version -m ./stayrtr
commit bf5793cf0fe897888f0dd78f5bb236db46a8fd18
./stayrtr: go1.22.3
	path	github.com/bgp/stayrtr/cmd/stayrtr
	mod	github.com/bgp/stayrtr	(devel)	
	dep	github.com/beorn7/perks	v1.0.1	h1:VlbKKnNfV8bJzeqoa4cOKqO6bYr3WgKZxO8Z16+hsOM=
	dep	github.com/cespare/xxhash/v2	v2.1.1	h1:6MnRN8NT7+YBpUIWxHtefFZOKTAPgGjpQSxqLNn0+qY=
	dep	github.com/golang/protobuf	v1.4.3	h1:JjCZWpVbqXDqFVmTfYWEVTMIYrL/NPdPSCHPJ0T/raM=
	dep	github.com/matttproud/golang_protobuf_extensions	v1.0.1	h1:4hp9jkHxhMHkqkrB3Ix0jegS5sx/RkqARlsWZ6pIwiU=
	dep	github.com/prometheus/client_golang	v1.11.1	h1:+4eQaD7vAZ6DsfsxB15hbE0odUjGI5ARs9yskGu1v4s=
	dep	github.com/prometheus/client_model	v0.2.0	h1:uq5h0d+GuxiXLJLNABMgp2qUWDPiLvgCzz2dUR+/W/M=
	dep	github.com/prometheus/common	v0.26.0	h1:iMAkS2TDoNWnKM+Kopnx/8tnEStIfpYA0ur0xQzzhMQ=
	dep	github.com/prometheus/procfs	v0.6.0	h1:mxy4L2jP6qMonqmq+aTtOx1ifVWUgG/TAmntgbh3xv4=
	dep	github.com/sirupsen/logrus	v1.8.1	h1:dJKuHgqk1NNQlqoA6BTlM1Wf9DOH3NBjQyu0h9+AZZE=
	dep	golang.org/x/crypto	v0.6.0	h1:qfktjS5LUO+fFKeJXZ+ikTRijMmljikvG68fpMMruSc=
	dep	golang.org/x/sys	v0.15.0	h1:h48lPFYpsTvQJZF4EKyI4aLHaev3CxivZmv7yZig9pc=
	dep	google.golang.org/protobuf	v1.26.0-rc.1	h1:7QnIQpGRHE5RnLKnESfDoxm2dTapTZua5a0kS0A+VXQ=
	build	-buildmode=exe
	build	-compiler=gc
	build	DefaultGODEBUG=httplaxcontentlength=1,httpmuxgo121=1,panicnil=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
	build	CGO_ENABLED=1
	build	CGO_CFLAGS=
	build	CGO_CPPFLAGS=
	build	CGO_CXXFLAGS=
	build	CGO_LDFLAGS=
	build	GOARCH=amd64
	build	GOOS=linux
	build	GOAMD64=v1
	build	vcs=git
	build	vcs.revision=bf5793cf0fe897888f0dd78f5bb236db46a8fd18
	build	vcs.time=2024-06-26T14:52:40Z
	build	vcs.modified=false
```

After abcaca9947c9e77fcc3a9fd330995cb232eacb84 makes it into a (pre-)release, you should be able to use the above method to view the revision `stayrtr` was based on.

**Comment by mrngm** [comment]
After extracting `/usr/bin/stayrtr` from https://github.com/bgp/stayrtr/releases/download/v0.5.1/stayrtr_0.5.1_amd64.deb:

```
$ sha256sum stayrtr && ./stayrtr -version
fced62afc99edf79314ea2ec0a0a027ba4b43c95fe346a601ccf77251c70fa05  stayrtr
StayRTR v0.5.1 (2023-03-01T14:37:13+0000)
```

That opens the question: what binary are you actually running?

**Comment by job** [comment]
> After extracting `/usr/bin/stayrtr` from https://github.com/bgp/stayrtr/releases/download/v0.5.1/stayrtr_0.5.1_amd64.deb:
> 
> ```
> $ sha256sum stayrtr && ./stayrtr -version
> fced62afc99edf79314ea2ec0a0a027ba4b43c95fe346a601ccf77251c70fa05  stayrtr
> StayRTR v0.5.1 (2023-03-01T14:37:13+0000)
> ```
> 
> That opens the question: what binary are you actually running?

Maybe something from Debian `.deb` repositories?

**Comment by mrngm** [comment]
It appears so:

```
$ curl -O http://ftp.de.debian.org/debian/pool/main/s/stayrtr/stayrtr_0.5.1-2+b1_amd64.deb
$ dpkg-deb -x stayrtr_0.5.1-2+b1_amd64.deb stayrtr-debstable
$ cd stayrtr-debstable/usr/bin/
$ sha256sum stayrtr && ./stayrtr -version
361e4b46b2d00a608154f033b94222966996f97615a992edab94eab6151cd47e  stayrtr
StayRTR  
```

**Comment by randomthingsandstuff** [comment]
job @'ed me so i guess i'm back..

if i understand right, we have like 3 ways this thing is built:

1. the usual golang build system
2. the happy makefile with the git
3. the happy makefile without the git

in case 1, which i am strongly going to support as the ultimate, premier, long-term way of doing things (until it makes sense ot me that it isn't and i'm philosophizing too much again), we can't derive the version info from git anyway.

in case 2, we can drag the version info automagically

in case 3, we don't have a git so lol whats the version again?

what i really really want is something like <version>~<git short commit hash> where version comes from the tag. in the absence of really being able to do that for mostly the same issues as case 1 and 3, we should just shove it in as a constant per job's patch and call it a day. if we are really lazy, maybe we can one day have the tag get autoadded when someone bumps the version variable or something.

so i merged job's patch. its an easy decision. its done and solves the problem for now. we will live to fight `--version` another day.
