### ISSUE TITLE
Fix the Docker Hub container thingy

### ISSUE THREAD

**Issue by randomthingsandstuff** [bgp/stayrtr#19]
Yeah, its been broken since we forked. I don't have a hub account and should probably think about getting one or something.

I want this done before we release the first (real) version... so let's see if we get it done within 5 versions :D

**Comment by ties** [comment]
I think we are publishing docker images. What's probably lacking is documenting that + actually tagging releases.

**Comment by randomthingsandstuff** [comment]
Oh nice! so I'll just need to update the docs to use rpki/stayrtr then. I'm guessing @job set this up or something.

**Comment by job** [comment]
Me and @robert-scheck have access to the Docker Hub account for the `rpki` org,

We're riding the free tier which permits 3 accounts: 2 humans and 1 robot. The robot is hooked up to this repo.

**Comment by lspgn** [comment]
My two cents
In GoFlow2, was able to use API keys and have the docker build inside Actions
https://github.com/netsampler/goflow2/blob/main/.github/workflows/docker-release.yaml

**Comment by job** [comment]
@lspgn we're using the API keys of a robot user called `rpkier`

**Comment by robert-scheck** [comment]
I've performed the Docker Open Source Community Application (which might wipe this limit as well), but we are still under evaluation.

And rpki-client uses also the GitHub Actions, thus I guess the same might work for stayrtr, too.

**Comment by ties** [comment]
> My two cents
> In GoFlow2, was able to use API keys and have the docker build inside Actions
> https://github.com/netsampler/goflow2/blob/main/.github/workflows/docker-release.yaml

Nice way of doing the ARM build and doing the releases on tags. Would be good to incorporate this for release tags as well.
(In general I've started to really appreciate GitHub actions)
