### ISSUE TITLE
Remove -verify option

### ISSUE THREAD

**Issue by job** [bgp/stayrtr#2]
Simplify the code by shifting responsibility of VRP transport to elsewhere

**Comment by job** [comment]
Yes. The JSON data is canonicalized in a specific way and then signed, but I think it should be left as a decision for the operator where to pull the VRP set from and how to safely transport it.

**Comment by randomthingsandstuff** [comment]
ok so more like only octorpki signs and we don't care. this is low priority till its time to refactor things.
