### ISSUE TITLE
docker-compose -f docker-compose-pkg.yml up - broke for me - Golang version and fpm options

### ISSUE THREAD

**Issue by auskai** [bgp/stayrtr#56]
I manually did this... Manually set STAYRTR_VERSION and removed --package dist/ in Makefile..

# Using Pre-release Tag 0.3.0

vi Makefile
STAYRTR_VERSION := 0.3.0
REPLACE --package dist/ with --maintainer "Human Fixes"
# debian bullseye
docker run -it --rm --name stayrtr_ruby -v "$PWD":/work ruby /bin/bash

apt-get update && apt-get install -y git make rpm golang \
               && gem install fpm && cd work && mkdir -p dist

make build-rtrmon
make build-rtrdump
make build-stayrtr
make package-rpm-stayrtr

mkdir -p dist/
fpm -s dir -t rpm -n stayrtr -v 0.3.0 \
--description "StayRTR: a RPKI-to-Router server" \
--url "https://github.com/bgp/stayrtr" \
--architecture x86_64 \
--license "BSD-3" \
--maintainer "Human Fixes" \
dist/stayrtr-0.3.0-linux-x86_64=/usr/bin/stayrtr \
package/stayrtr.service=/lib/systemd/system/stayrtr.service \
package/stayrtr.env=/etc/default/stayrtr \
dist/rtrdump-0.3.0-linux-x86_64=/usr/bin/rtrdump \
dist/rtrmon-0.3.0-linux-x86_64=/usr/bin/rtrmon

# Master wanted GoLang 1.16+ not in Ruby

git clone https://github.com/bgp/stayrtr.git

docker pull ubuntu:22.04
docker run -it --rm --name stayrtr_ubuntu -v "$PWD":/work ubuntu:22.04 /bin/bash
apt-get update && apt-get install -y git make rpm golang ruby \
        && gem install fpm && cd work && mkdir -p dist

vi Makefile
STAYRTR_VERSION := 0.3.1
REPLACE --package dist/ with --maintainer "Human Fixes"

make build-rtrmon
make build-rtrdump
make build-stayrtr
make package-rpm-stayrtr

mkdir -p dist/
fpm -s dir -t rpm -n stayrtr -v 0.3.1 \
--description "StayRTR: a RPKI-to-Router server" \
--url "https://github.com/bgp/stayrtr" \
--architecture x86_64 \
--license "BSD-3" \
--maintainer "Human Fixes" \
dist/stayrtr-0.3.1-linux-x86_64=/usr/bin/stayrtr \
package/stayrtr.service=/lib/systemd/system/stayrtr.service \
package/stayrtr.env=/etc/default/stayrtr \
dist/rtrdump-0.3.1-linux-x86_64=/usr/bin/rtrdump \
dist/rtrmon-0.3.1-linux-x86_64=/usr/bin/rtrmon

Installed OK... 
rpm2cpio stayrtr-0.3.1-1.x86_64.rpm | cpio -imdv

# https://fpm.readthedocs.io/en/latest/getting-started.html

**Comment by benjojo** [comment]
Hi, I've improved a bunch of packaging stuff in the mean time, I _assume_ this issue wont' happen anymore, but please comment/reopen if it does
