### ISSUE TITLE
Duplicate VRP served out

### ISSUE THREAD

**Issue by wouterprins** [bgp/stayrtr#93]
Running StayRTR v0.5.0 and noticed a resetting RTR session today:

```
27076 2023/02/28 20:03:03.344 CET MINOR: RPKI #2001 management RPKI
"Rpki Session state on x.x.x.x changed to down due to fatalErrorCode"

27075 2023/02/28 20:03:03.344 CET CRITICAL: LOGGER #2002 Base A:RPKI:UNUSUAL_ERROR
"Slot A: rpkiValidatePrefix: x.x.x.x:Duplicate V6 prefix 2a02:88d:4004:: prefix len 48"
```
The output of rpki-client shows one entry for the mentioned prefix in the json file. When issuing a rtrdump (`./rtrdump -file debug.json -connect 127.0.0.1:3323`) towards StayRTR we can see a duplicate entry in the debug.json file:

`{"prefix":"2a02:88d:4004::/48","maxLength":48,"asn":48695},{"prefix":"2a02:88d:4004::/48","maxLength":48,"asn":48695}`

We have not been able to reproduce this issue so far.. :)

**Comment by benjojo** [comment]
Are you running v0.5.0 as tagged on docker? There are a bunch of known issues with that right now, assuming you are, can you try running this latest commit and reporting back of you see this again:

https://github.com/bgp/stayrtr/commit/62f59527762a908a74664b8ce1fc69304f80f84b

**Comment by benjojo** [comment]
I have tagged 0.5.1 and uploaded releases https://github.com/bgp/stayrtr/releases/tag/v0.5.1

**Comment by wouterprins** [comment]
Much appreciated and just updated it.. 👍

**Comment by wouterprins** [comment]
Running v0.5.0 and v0.5.1 in parallel, both are working ok for last two days. I'm waiting for the v0.5.0 instance to send out the duplicate VRP to be able to determine if the v0.5.1 RTR session remains up. We'll keep it running for a while.

Feel free to close this issue. If we see a re-occurrence with v0.5.1 i'll open up a new one. Thanks again. :)
